[project]
name = "tnp-crop"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "hydra-core>=1.3.2",
  "hydra-colorlog>=1.2.0",
  "rootutils",
  "rich",
  "python-dotenv",
  "requests>=2.34.2",
  "pandas>=2.3.3",
]

[project.optional-dependencies]
train = [
  "torch>=2.13.0",
  "pytorch-lightning>=2.2",
  "torchmetrics>=1.3",
]
data = [
    "requests>=2.34.2",
]
dev = [
  "pytest",
  "pre-commit",
]

[tool.pytest.ini_options]
addopts = [
  "--color=yes",
  "--durations=0",
  "--strict-markers",
  "--doctest-modules",
]
filterwarnings = [
  "ignore::DeprecationWarning",
  "ignore::UserWarning",
]
log_cli = "True"
markers = [
  "slow: slow tests",
]
minversion = "6.0"

[tool.coverage.report]
exclude_lines = [
    "pragma: nocover",
    "raise NotImplementedError",
    "raise NotImplementedError()",
    "if __name__ == .__main__.:",
]
