{
      "RDMSOL": 100,
      "SoilProfileDescription": {
            "PFWiltingPoint": 4.2,
            "PFFieldCapacity": 2.0,
            "SurfaceConductivity": 70,
            "GroundWater": false,
            "SoilLayers": [
                  {
                        "Thickness": 5,
                        "CNRatioSOMI": 14.769647696476966,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.06322,
                        "RHOD": 0.91,
                        "Soil_pH": 6.5,
                        "SMfromPF": [
                              -1.0,
                              0.5775,
                              1.0,
                              0.5567,
                              1.3,
                              0.5368,
                              1.7,
                              0.4928,
                              2.0,
                              0.45,
                              2.3,
                              0.4045,
                              2.4,
                              0.3896,
                              2.7,
                              0.3465,
                              3.0,
                              0.3073,
                              3.3,
                              0.2723,
                              3.7,
                              0.2316,
                              4.0,
                              0.2052,
                              4.2,
                              0.1894,
                              6.0,
                              0.0938
                        ],
                        "CONDfromPF": [
                              -1.0,
                              1.4214,
                              1.0,
                              0.4867,
                              1.3,
                              0.1508,
                              1.7,
                              -0.4241,
                              2.0,
                              -0.9328,
                              2.3,
                              -1.4827,
                              2.4,
                              -1.6717,
                              2.7,
                              -2.2484,
                              3.0,
                              -2.8336,
                              3.3,
                              -3.4226,
                              3.7,
                              -4.2105,
                              4.0,
                              -4.8022,
                              4.2,
                              -5.1968,
                              6.0,
                              -8.7494
                        ]
                  },
                  {
                        "Thickness": 10,
                        "CNRatioSOMI": 10.252100840336135,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.021227999999999997,
                        "RHOD": 1.23,
                        "Soil_pH": 6.6,
                        "SMfromPF": [
                              -1.0,
                              0.4854,
                              1.0,
                              0.4662,
                              1.3,
                              0.4467,
                              1.7,
                              0.403,
                              2.0,
                              0.3607,
                              2.3,
                              0.3166,
                              2.4,
                              0.3023,
                              2.7,
                              0.2621,
                              3.0,
                              0.2265,
                              3.3,
                              0.1956,
                              3.7,
                              0.161,
                              4.0,
                              0.1393,
                              4.2,
                              0.1265,
                              6.0,
                              0.0558
                        ],
                        "CONDfromPF": [
                              -1.0,
                              1.4152,
                              1.0,
                              0.5474,
                              1.3,
                              0.221,
                              1.7,
                              -0.3445,
                              2.0,
                              -0.8479,
                              2.3,
                              -1.3925,
                              2.4,
                              -1.5796,
                              2.7,
                              -2.1502,
                              3.0,
                              -2.7286,
                              3.3,
                              -3.3106,
                              3.7,
                              -4.0887,
                              4.0,
                              -4.673,
                              4.2,
                              -5.0626,
                              6.0,
                              -8.5702
                        ]
                  },
                  {
                        "Thickness": 15,
                        "CNRatioSOMI": 17.456140350877195,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.034626000000000004,
                        "RHOD": 1.37,
                        "Soil_pH": 6.7,
                        "SMfromPF": [
                              -1.0,
                              0.4399,
                              1.0,
                              0.424,
                              1.3,
                              0.4088,
                              1.7,
                              0.3755,
                              2.0,
                              0.3432,
                              2.3,
                              0.309,
                              2.4,
                              0.2978,
                              2.7,
                              0.2654,
                              3.0,
                              0.236,
                              3.3,
                              0.2096,
                              3.7,
                              0.1789,
                              4.0,
                              0.159,
                              4.2,
                              0.147,
                              6.0,
                              0.0745
                        ],
                        "CONDfromPF": [
                              -1.0,
                              0.9984,
                              1.0,
                              0.0671,
                              1.3,
                              -0.2589,
                              1.7,
                              -0.8077,
                              2.0,
                              -1.2872,
                              2.3,
                              -1.802,
                              2.4,
                              -1.9784,
                              2.7,
                              -2.516,
                              3.0,
                              -3.0607,
                              3.3,
                              -3.6086,
                              3.7,
                              -4.3413,
                              4.0,
                              -4.8915,
                              4.2,
                              -5.2584,
                              6.0,
                              -8.5616
                        ]
                  },
                  {
                        "Thickness": 30,
                        "CNRatioSOMI": 13.856209150326796,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.024592000000000003,
                        "RHOD": 1.58,
                        "Soil_pH": 6.7,
                        "SMfromPF": [
                              -1.0,
                              0.3802,
                              1.0,
                              0.3707,
                              1.3,
                              0.3616,
                              1.7,
                              0.3409,
                              2.0,
                              0.3194,
                              2.3,
                              0.2954,
                              2.4,
                              0.2872,
                              2.7,
                              0.2631,
                              3.0,
                              0.2402,
                              3.3,
                              0.2191,
                              3.7,
                              0.1936,
                              4.0,
                              0.1766,
                              4.2,
                              0.1661,
                              6.0,
                              0.0968
                        ],
                        "CONDfromPF": [
                              -1.0,
                              0.674,
                              1.0,
                              -0.2434,
                              1.3,
                              -0.5429,
                              1.7,
                              -1.0419,
                              2.0,
                              -1.4785,
                              2.3,
                              -1.9497,
                              2.4,
                              -2.1117,
                              2.7,
                              -2.6066,
                              3.0,
                              -3.1093,
                              3.3,
                              -3.6158,
                              3.7,
                              -4.2937,
                              4.0,
                              -4.8028,
                              4.2,
                              -5.1424,
                              6.0,
                              -8.2002
                        ]
                  },
                  {
                        "Thickness": 40,
                        "CNRatioSOMI": 10.718954248366012,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.019023999999999996,
                        "RHOD": 1.64,
                        "Soil_pH": 6.8,
                        "SMfromPF": [
                              -1.0,
                              0.3629,
                              1.0,
                              0.3548,
                              1.3,
                              0.347,
                              1.7,
                              0.3283,
                              2.0,
                              0.3085,
                              2.3,
                              0.2857,
                              2.4,
                              0.2779,
                              2.7,
                              0.2546,
                              3.0,
                              0.2324,
                              3.3,
                              0.2119,
                              3.7,
                              0.1872,
                              4.0,
                              0.1706,
                              4.2,
                              0.1604,
                              6.0,
                              0.0932
                        ],
                        "CONDfromPF": [
                              -1.0,
                              0.6441,
                              1.0,
                              -0.236,
                              1.3,
                              -0.5238,
                              1.7,
                              -1.0078,
                              2.0,
                              -1.4362,
                              2.3,
                              -1.9023,
                              2.4,
                              -2.0631,
                              2.7,
                              -2.5557,
                              3.0,
                              -3.0572,
                              3.3,
                              -3.563,
                              3.7,
                              -4.2402,
                              4.0,
                              -4.749,
                              4.2,
                              -5.0884,
                              6.0,
                              -8.1446
                        ]
                  }
            ],
            "SubSoilType": {
                  "CNRatioSOMI": 10.718954248366012,
                  "CRAIRC": 0.03,
                  "FSOMI": 0.019023999999999996,
                  "RHOD": 1.64,
                  "Soil_pH": 6.8,
                  "Thickness": 40,
                  "SMfromPF": [
                        -1.0,
                        0.3629,
                        1.0,
                        0.3548,
                        1.3,
                        0.347,
                        1.7,
                        0.3283,
                        2.0,
                        0.3085,
                        2.3,
                        0.2857,
                        2.4,
                        0.2779,
                        2.7,
                        0.2546,
                        3.0,
                        0.2324,
                        3.3,
                        0.2119,
                        3.7,
                        0.1872,
                        4.0,
                        0.1706,
                        4.2,
                        0.1604,
                        6.0,
                        0.0932
                  ],
                  "CONDfromPF": [
                        -1.0,
                        0.6441,
                        1.0,
                        -0.236,
                        1.3,
                        -0.5238,
                        1.7,
                        -1.0078,
                        2.0,
                        -1.4362,
                        2.3,
                        -1.9023,
                        2.4,
                        -2.0631,
                        2.7,
                        -2.5557,
                        3.0,
                        -3.0572,
                        3.3,
                        -3.563,
                        3.7,
                        -4.2402,
                        4.0,
                        -4.749,
                        4.2,
                        -5.0884,
                        6.0,
                        -8.1446
                  ]
            }
      }
}