{
      "RDMSOL": 200,
      "SoilProfileDescription": {
            "PFWiltingPoint": 4.2,
            "PFFieldCapacity": 2.0,
            "SurfaceConductivity": 70,
            "GroundWater": false,
            "SoilLayers": [
                  {
                        "Thickness": 5,
                        "CNRatioSOMI": 13.60248447204969,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.038106,
                        "RHOD": 1.01,
                        "Soil_pH": 7.0,
                        "SMfromPF": [
                              -1.0,
                              0.5589,
                              1.0,
                              0.5434,
                              1.3,
                              0.528,
                              1.7,
                              0.4924,
                              2.0,
                              0.4557,
                              2.3,
                              0.4151,
                              2.4,
                              0.4014,
                              2.7,
                              0.3613,
                              3.0,
                              0.3241,
                              3.3,
                              0.2903,
                              3.7,
                              0.2505,
                              4.0,
                              0.2243,
                              4.2,
                              0.2084,
                              6.0,
                              0.1092
                        ],
                        "CONDfromPF": [
                              -1.0,
                              1.3079,
                              1.0,
                              0.4146,
                              1.3,
                              0.1022,
                              1.7,
                              -0.4363,
                              2.0,
                              -0.9195,
                              2.3,
                              -1.4478,
                              2.4,
                              -1.6304,
                              2.7,
                              -2.1896,
                              3.0,
                              -2.759,
                              3.3,
                              -3.3331,
                              3.7,
                              -4.1016,
                              4.0,
                              -4.679,
                              4.2,
                              -5.0642,
                              6.0,
                              -8.5319
                        ]
                  },
                  {
                        "Thickness": 10,
                        "CNRatioSOMI": 20.833333333333332,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.02465,
                        "RHOD": 1.13,
                        "Soil_pH": 7.2,
                        "SMfromPF": [
                              -1.0,
                              0.5251,
                              1.0,
                              0.5101,
                              1.3,
                              0.4953,
                              1.7,
                              0.4611,
                              2.0,
                              0.4259,
                              2.3,
                              0.3871,
                              2.4,
                              0.3741,
                              2.7,
                              0.3361,
                              3.0,
                              0.3009,
                              3.3,
                              0.269,
                              3.7,
                              0.2315,
                              4.0,
                              0.2069,
                              4.2,
                              0.1921,
                              6.0,
                              0.0998
                        ],
                        "CONDfromPF": [
                              -1.0,
                              1.2563,
                              1.0,
                              0.3665,
                              1.3,
                              0.0561,
                              1.7,
                              -0.4764,
                              2.0,
                              -0.9521,
                              2.3,
                              -1.4707,
                              2.4,
                              -1.6497,
                              2.7,
                              -2.1975,
                              3.0,
                              -2.7548,
                              3.3,
                              -3.3164,
                              3.7,
                              -4.0682,
                              4.0,
                              -4.633,
                              4.2,
                              -5.0097,
                              6.0,
                              -8.4012
                        ]
                  },
                  {
                        "Thickness": 15,
                        "CNRatioSOMI": 30.67605633802817,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.06316200000000001,
                        "RHOD": 1.13,
                        "Soil_pH": 7.2,
                        "SMfromPF": [
                              -1.0,
                              0.5143,
                              1.0,
                              0.4993,
                              1.3,
                              0.486,
                              1.7,
                              0.4578,
                              2.0,
                              0.4303,
                              2.3,
                              0.4005,
                              2.4,
                              0.3905,
                              2.7,
                              0.3609,
                              3.0,
                              0.3328,
                              3.3,
                              0.3066,
                              3.7,
                              0.2748,
                              4.0,
                              0.2531,
                              4.2,
                              0.2396,
                              6.0,
                              0.1474
                        ],
                        "CONDfromPF": [
                              -1.0,
                              0.7195,
                              1.0,
                              -0.3204,
                              1.3,
                              -0.6637,
                              1.7,
                              -1.2328,
                              2.0,
                              -1.7263,
                              2.3,
                              -2.2555,
                              2.4,
                              -2.4368,
                              2.7,
                              -2.9899,
                              3.0,
                              -3.5509,
                              3.3,
                              -4.1157,
                              3.7,
                              -4.8713,
                              4.0,
                              -5.4388,
                              4.2,
                              -5.8173,
                              6.0,
                              -9.2254
                        ]
                  },
                  {
                        "Thickness": 30,
                        "CNRatioSOMI": 23.03317535545024,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.056376,
                        "RHOD": 1.07,
                        "Soil_pH": 7.2,
                        "SMfromPF": [
                              -1.0,
                              0.5363,
                              1.0,
                              0.5205,
                              1.3,
                              0.5063,
                              1.7,
                              0.4757,
                              2.0,
                              0.446,
                              2.3,
                              0.4136,
                              2.4,
                              0.4027,
                              2.7,
                              0.3707,
                              3.0,
                              0.3404,
                              3.3,
                              0.3123,
                              3.7,
                              0.2783,
                              4.0,
                              0.2552,
                              4.2,
                              0.2409,
                              6.0,
                              0.1445
                        ],
                        "CONDfromPF": [
                              -1.0,
                              0.9132,
                              1.0,
                              -0.1095,
                              1.3,
                              -0.4505,
                              1.7,
                              -1.019,
                              2.0,
                              -1.5141,
                              2.3,
                              -2.0461,
                              2.4,
                              -2.2286,
                              2.7,
                              -2.7855,
                              3.0,
                              -3.3505,
                              3.3,
                              -3.9194,
                              3.7,
                              -4.6805,
                              4.0,
                              -5.2522,
                              4.2,
                              -5.6335,
                              6.0,
                              -9.0667
                        ]
                  },
                  {
                        "Thickness": 40,
                        "CNRatioSOMI": 22.028301886792452,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.054172000000000005,
                        "RHOD": 1.14,
                        "Soil_pH": 7.2,
                        "SMfromPF": [
                              -1.0,
                              0.514,
                              1.0,
                              0.4985,
                              1.3,
                              0.4847,
                              1.7,
                              0.4555,
                              2.0,
                              0.4272,
                              2.3,
                              0.3966,
                              2.4,
                              0.3863,
                              2.7,
                              0.3561,
                              3.0,
                              0.3275,
                              3.3,
                              0.3009,
                              3.7,
                              0.2687,
                              4.0,
                              0.2468,
                              4.2,
                              0.2333,
                              6.0,
                              0.1413
                        ],
                        "CONDfromPF": [
                              -1.0,
                              0.8595,
                              1.0,
                              -0.176,
                              1.3,
                              -0.5183,
                              1.7,
                              -1.0849,
                              2.0,
                              -1.5754,
                              2.3,
                              -2.1006,
                              2.4,
                              -2.2805,
                              2.7,
                              -2.8289,
                              3.0,
                              -3.3848,
                              3.3,
                              -3.9444,
                              3.7,
                              -4.693,
                              4.0,
                              -5.2553,
                              4.2,
                              -5.6302,
                              6.0,
                              -9.0064
                        ]
                  },
                  {
                        "Thickness": 100,
                        "CNRatioSOMI": 20.043103448275865,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.05394,
                        "RHOD": 1.16,
                        "Soil_pH": 7.1,
                        "SMfromPF": [
                              -1.0,
                              0.515,
                              1.0,
                              0.5021,
                              1.3,
                              0.4909,
                              1.7,
                              0.4674,
                              2.0,
                              0.4446,
                              2.3,
                              0.4194,
                              2.4,
                              0.4109,
                              2.7,
                              0.3855,
                              3.0,
                              0.3609,
                              3.3,
                              0.3377,
                              3.7,
                              0.3089,
                              4.0,
                              0.2889,
                              4.2,
                              0.2762,
                              6.0,
                              0.1855
                        ],
                        "CONDfromPF": [
                              -1.0,
                              0.5318,
                              1.0,
                              -0.5505,
                              1.3,
                              -0.898,
                              1.7,
                              -1.4695,
                              2.0,
                              -1.9629,
                              2.3,
                              -2.4912,
                              2.4,
                              -2.6722,
                              2.7,
                              -3.2244,
                              3.0,
                              -3.7847,
                              3.3,
                              -4.3488,
                              3.7,
                              -5.1037,
                              4.0,
                              -5.6707,
                              4.2,
                              -6.0489,
                              6.0,
                              -9.4545
                        ]
                  }
            ],
            "SubSoilType": {
                  "CNRatioSOMI": 20.043103448275865,
                  "CRAIRC": 0.03,
                  "FSOMI": 0.05394,
                  "RHOD": 1.16,
                  "Soil_pH": 7.1,
                  "Thickness": 100,
                  "SMfromPF": [
                        -1.0,
                        0.515,
                        1.0,
                        0.5021,
                        1.3,
                        0.4909,
                        1.7,
                        0.4674,
                        2.0,
                        0.4446,
                        2.3,
                        0.4194,
                        2.4,
                        0.4109,
                        2.7,
                        0.3855,
                        3.0,
                        0.3609,
                        3.3,
                        0.3377,
                        3.7,
                        0.3089,
                        4.0,
                        0.2889,
                        4.2,
                        0.2762,
                        6.0,
                        0.1855
                  ],
                  "CONDfromPF": [
                        -1.0,
                        0.5318,
                        1.0,
                        -0.5505,
                        1.3,
                        -0.898,
                        1.7,
                        -1.4695,
                        2.0,
                        -1.9629,
                        2.3,
                        -2.4912,
                        2.4,
                        -2.6722,
                        2.7,
                        -3.2244,
                        3.0,
                        -3.7847,
                        3.3,
                        -4.3488,
                        3.7,
                        -5.1037,
                        4.0,
                        -5.6707,
                        4.2,
                        -6.0489,
                        6.0,
                        -9.4545
                  ]
            }
      }
}