{
      "RDMSOL": 200,
      "SoilProfileDescription": {
            "PFWiltingPoint": 4.2,
            "PFFieldCapacity": 2.0,
            "SurfaceConductivity": 70,
            "GroundWater": false,
            "SoilLayers": [
                  {
                        "Thickness": 5,
                        "CNRatioSOMI": 16.356107660455486,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.04582,
                        "RHOD": 1.02,
                        "Soil_pH": 7.2,
                        "SMfromPF": [
                              -1.0,
                              0.5513,
                              1.0,
                              0.5351,
                              1.3,
                              0.5194,
                              1.7,
                              0.4837,
                              2.0,
                              0.4475,
                              2.3,
                              0.4078,
                              2.4,
                              0.3945,
                              2.7,
                              0.3557,
                              3.0,
                              0.3196,
                              3.3,
                              0.2868,
                              3.7,
                              0.2481,
                              4.0,
                              0.2226,
                              4.2,
                              0.2071,
                              6.0,
                              0.1098
                        ],
                        "CONDfromPF": [
                              -1.0,
                              1.1142,
                              1.0,
                              0.1957,
                              1.3,
                              -0.1248,
                              1.7,
                              -0.6739,
                              2.0,
                              -1.1634,
                              2.3,
                              -1.6961,
                              2.4,
                              -1.8798,
                              2.7,
                              -2.4419,
                              3.0,
                              -3.0135,
                              3.3,
                              -3.5895,
                              3.7,
                              -4.3605,
                              4.0,
                              -4.9397,
                              4.2,
                              -5.326,
                              6.0,
                              -8.8041
                        ]
                  },
                  {
                        "Thickness": 10,
                        "CNRatioSOMI": 16.59217877094972,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.017225999999999998,
                        "RHOD": 1.14,
                        "Soil_pH": 7.3,
                        "SMfromPF": [
                              -1.0,
                              0.521,
                              1.0,
                              0.5074,
                              1.3,
                              0.4929,
                              1.7,
                              0.4573,
                              2.0,
                              0.419,
                              2.3,
                              0.3758,
                              2.4,
                              0.3613,
                              2.7,
                              0.3191,
                              3.0,
                              0.2804,
                              3.3,
                              0.246,
                              3.7,
                              0.2065,
                              4.0,
                              0.1812,
                              4.2,
                              0.1661,
                              6.0,
                              0.0781
                        ],
                        "CONDfromPF": [
                              -1.0,
                              1.271,
                              1.0,
                              0.4711,
                              1.3,
                              0.1797,
                              1.7,
                              -0.3353,
                              2.0,
                              -0.8088,
                              2.3,
                              -1.3339,
                              2.4,
                              -1.5165,
                              2.7,
                              -2.0774,
                              3.0,
                              -2.65,
                              3.3,
                              -3.2279,
                              3.7,
                              -4.002,
                              4.0,
                              -4.5835,
                              4.2,
                              -4.9715,
                              6.0,
                              -8.4644
                        ]
                  },
                  {
                        "Thickness": 15,
                        "CNRatioSOMI": 18.404255319148938,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.040136000000000005,
                        "RHOD": 1.14,
                        "Soil_pH": 7.3,
                        "SMfromPF": [
                              -1.0,
                              0.5154,
                              1.0,
                              0.5009,
                              1.3,
                              0.487,
                              1.7,
                              0.4553,
                              2.0,
                              0.4231,
                              2.3,
                              0.3876,
                              2.4,
                              0.3757,
                              2.7,
                              0.3407,
                              3.0,
                              0.3079,
                              3.3,
                              0.278,
                              3.7,
                              0.2424,
                              4.0,
                              0.2187,
                              4.2,
                              0.2043,
                              6.0,
                              0.112
                        ],
                        "CONDfromPF": [
                              -1.0,
                              0.9318,
                              1.0,
                              0.0056,
                              1.3,
                              -0.3119,
                              1.7,
                              -0.852,
                              2.0,
                              -1.3314,
                              2.3,
                              -1.8523,
                              2.4,
                              -2.0318,
                              2.7,
                              -2.5808,
                              3.0,
                              -3.1392,
                              3.3,
                              -3.7018,
                              3.7,
                              -4.455,
                              4.0,
                              -5.0207,
                              4.2,
                              -5.3981,
                              6.0,
                              -8.7957
                        ]
                  },
                  {
                        "Thickness": 30,
                        "CNRatioSOMI": 13.024282560706402,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.03422,
                        "RHOD": 1.09,
                        "Soil_pH": 7.2,
                        "SMfromPF": [
                              -1.0,
                              0.5349,
                              1.0,
                              0.5206,
                              1.3,
                              0.5065,
                              1.7,
                              0.4739,
                              2.0,
                              0.4401,
                              2.3,
                              0.4023,
                              2.4,
                              0.3896,
                              2.7,
                              0.3522,
                              3.0,
                              0.3172,
                              3.3,
                              0.2853,
                              3.7,
                              0.2475,
                              4.0,
                              0.2225,
                              4.2,
                              0.2073,
                              6.0,
                              0.1112
                        ],
                        "CONDfromPF": [
                              -1.0,
                              1.0893,
                              1.0,
                              0.1935,
                              1.3,
                              -0.1165,
                              1.7,
                              -0.6491,
                              2.0,
                              -1.1265,
                              2.3,
                              -1.6484,
                              2.4,
                              -1.8288,
                              2.7,
                              -2.3816,
                              3.0,
                              -2.9445,
                              3.3,
                              -3.5121,
                              3.7,
                              -4.2721,
                              4.0,
                              -4.8431,
                              4.2,
                              -5.224,
                              6.0,
                              -8.6534
                        ]
                  },
                  {
                        "Thickness": 40,
                        "CNRatioSOMI": 13.792325056433409,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.035438000000000004,
                        "RHOD": 1.19,
                        "Soil_pH": 7.2,
                        "SMfromPF": [
                              -1.0,
                              0.5,
                              1.0,
                              0.4856,
                              1.3,
                              0.4717,
                              1.7,
                              0.4399,
                              2.0,
                              0.4076,
                              2.3,
                              0.372,
                              2.4,
                              0.36,
                              2.7,
                              0.3251,
                              3.0,
                              0.2925,
                              3.3,
                              0.2629,
                              3.7,
                              0.2279,
                              4.0,
                              0.2048,
                              4.2,
                              0.1907,
                              6.0,
                              0.1021
                        ],
                        "CONDfromPF": [
                              -1.0,
                              0.9454,
                              1.0,
                              0.0344,
                              1.3,
                              -0.2796,
                              1.7,
                              -0.8148,
                              2.0,
                              -1.2902,
                              2.3,
                              -1.8067,
                              2.4,
                              -1.9847,
                              2.7,
                              -2.5292,
                              3.0,
                              -3.0828,
                              3.3,
                              -3.6406,
                              3.7,
                              -4.3872,
                              4.0,
                              -4.948,
                              4.2,
                              -5.3221,
                              6.0,
                              -8.69
                        ]
                  },
                  {
                        "Thickness": 100,
                        "CNRatioSOMI": 13.524416135881104,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.03694600000000001,
                        "RHOD": 1.2,
                        "Soil_pH": 7.2,
                        "SMfromPF": [
                              -1.0,
                              0.5055,
                              1.0,
                              0.4919,
                              1.3,
                              0.4795,
                              1.7,
                              0.4522,
                              2.0,
                              0.4251,
                              2.3,
                              0.3952,
                              2.4,
                              0.385,
                              2.7,
                              0.3551,
                              3.0,
                              0.3267,
                              3.3,
                              0.3002,
                              3.7,
                              0.2681,
                              4.0,
                              0.2463,
                              4.2,
                              0.2327,
                              6.0,
                              0.141
                        ],
                        "CONDfromPF": [
                              -1.0,
                              0.8383,
                              1.0,
                              -0.1584,
                              1.3,
                              -0.4884,
                              1.7,
                              -1.0405,
                              2.0,
                              -1.5239,
                              2.3,
                              -2.0452,
                              2.4,
                              -2.2244,
                              2.7,
                              -2.7718,
                              3.0,
                              -3.3278,
                              3.3,
                              -3.8879,
                              3.7,
                              -4.6376,
                              4.0,
                              -5.2007,
                              4.2,
                              -5.5763,
                              6.0,
                              -8.9583
                        ]
                  }
            ],
            "SubSoilType": {
                  "CNRatioSOMI": 13.524416135881104,
                  "CRAIRC": 0.03,
                  "FSOMI": 0.03694600000000001,
                  "RHOD": 1.2,
                  "Soil_pH": 7.2,
                  "Thickness": 100,
                  "SMfromPF": [
                        -1.0,
                        0.5055,
                        1.0,
                        0.4919,
                        1.3,
                        0.4795,
                        1.7,
                        0.4522,
                        2.0,
                        0.4251,
                        2.3,
                        0.3952,
                        2.4,
                        0.385,
                        2.7,
                        0.3551,
                        3.0,
                        0.3267,
                        3.3,
                        0.3002,
                        3.7,
                        0.2681,
                        4.0,
                        0.2463,
                        4.2,
                        0.2327,
                        6.0,
                        0.141
                  ],
                  "CONDfromPF": [
                        -1.0,
                        0.8383,
                        1.0,
                        -0.1584,
                        1.3,
                        -0.4884,
                        1.7,
                        -1.0405,
                        2.0,
                        -1.5239,
                        2.3,
                        -2.0452,
                        2.4,
                        -2.2244,
                        2.7,
                        -2.7718,
                        3.0,
                        -3.3278,
                        3.3,
                        -3.8879,
                        3.7,
                        -4.6376,
                        4.0,
                        -5.2007,
                        4.2,
                        -5.5763,
                        6.0,
                        -8.9583
                  ]
            }
      }
}