{
      "RDMSOL": 200,
      "SoilProfileDescription": {
            "PFWiltingPoint": 4.2,
            "PFFieldCapacity": 2.0,
            "SurfaceConductivity": 70,
            "GroundWater": false,
            "SoilLayers": [
                  {
                        "Thickness": 5,
                        "CNRatioSOMI": 13.91038696537678,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.039613999999999996,
                        "RHOD": 1.21,
                        "Soil_pH": 7.3,
                        "SMfromPF": [
                              -1.0,
                              0.4933,
                              1.0,
                              0.4759,
                              1.3,
                              0.4603,
                              1.7,
                              0.4275,
                              2.0,
                              0.3963,
                              2.3,
                              0.3632,
                              2.4,
                              0.3523,
                              2.7,
                              0.3204,
                              3.0,
                              0.2908,
                              3.3,
                              0.2637,
                              3.7,
                              0.2314,
                              4.0,
                              0.2098,
                              4.2,
                              0.1966,
                              6.0,
                              0.1108
                        ],
                        "CONDfromPF": [
                              -1.0,
                              1.0612,
                              1.0,
                              0.0442,
                              1.3,
                              -0.2969,
                              1.7,
                              -0.8596,
                              2.0,
                              -1.3438,
                              2.3,
                              -1.8598,
                              2.4,
                              -2.0362,
                              2.7,
                              -2.573,
                              3.0,
                              -3.1163,
                              3.3,
                              -3.6628,
                              3.7,
                              -4.3935,
                              4.0,
                              -4.9421,
                              4.2,
                              -5.308,
                              6.0,
                              -8.6021
                        ]
                  },
                  {
                        "Thickness": 10,
                        "CNRatioSOMI": 10.75268817204301,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.0116,
                        "RHOD": 1.32,
                        "Soil_pH": 7.4,
                        "SMfromPF": [
                              -1.0,
                              0.4663,
                              1.0,
                              0.4491,
                              1.3,
                              0.4325,
                              1.7,
                              0.396,
                              2.0,
                              0.3607,
                              2.3,
                              0.3234,
                              2.4,
                              0.3111,
                              2.7,
                              0.2761,
                              3.0,
                              0.2442,
                              3.3,
                              0.2159,
                              3.7,
                              0.1832,
                              4.0,
                              0.162,
                              4.2,
                              0.1494,
                              6.0,
                              0.0737
                        ],
                        "CONDfromPF": [
                              -1.0,
                              1.2729,
                              1.0,
                              0.352,
                              1.3,
                              0.0265,
                              1.7,
                              -0.5231,
                              2.0,
                              -1.0042,
                              2.3,
                              -1.5209,
                              2.4,
                              -1.698,
                              2.7,
                              -2.2377,
                              3.0,
                              -2.7845,
                              3.3,
                              -3.3346,
                              3.7,
                              -4.0701,
                              4.0,
                              -4.6224,
                              4.2,
                              -4.9907,
                              6.0,
                              -8.3065
                        ]
                  },
                  {
                        "Thickness": 15,
                        "CNRatioSOMI": 14.226415094339623,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.021866000000000003,
                        "RHOD": 1.4,
                        "Soil_pH": 7.4,
                        "SMfromPF": [
                              -1.0,
                              0.4388,
                              1.0,
                              0.4243,
                              1.3,
                              0.4109,
                              1.7,
                              0.3816,
                              2.0,
                              0.3531,
                              2.3,
                              0.3225,
                              2.4,
                              0.3123,
                              2.7,
                              0.2828,
                              3.0,
                              0.2553,
                              3.3,
                              0.2303,
                              3.7,
                              0.2007,
                              4.0,
                              0.1811,
                              4.2,
                              0.1692,
                              6.0,
                              0.0929
                        ],
                        "CONDfromPF": [
                              -1.0,
                              0.9614,
                              1.0,
                              0.0006,
                              1.3,
                              -0.3212,
                              1.7,
                              -0.8541,
                              2.0,
                              -1.3149,
                              2.3,
                              -1.8076,
                              2.4,
                              -1.9762,
                              2.7,
                              -2.4898,
                              3.0,
                              -3.0099,
                              3.3,
                              -3.5332,
                              3.7,
                              -4.2329,
                              4.0,
                              -4.7583,
                              4.2,
                              -5.1087,
                              6.0,
                              -8.2635
                        ]
                  },
                  {
                        "Thickness": 30,
                        "CNRatioSOMI": 11.77049180327869,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.020822,
                        "RHOD": 1.43,
                        "Soil_pH": 7.6,
                        "SMfromPF": [
                              -1.0,
                              0.4298,
                              1.0,
                              0.4166,
                              1.3,
                              0.4041,
                              1.7,
                              0.3765,
                              2.0,
                              0.3492,
                              2.3,
                              0.3195,
                              2.4,
                              0.3095,
                              2.7,
                              0.2805,
                              3.0,
                              0.2535,
                              3.3,
                              0.2289,
                              3.7,
                              0.1997,
                              4.0,
                              0.1803,
                              4.2,
                              0.1685,
                              6.0,
                              0.0929
                        ],
                        "CONDfromPF": [
                              -1.0,
                              0.9026,
                              1.0,
                              -0.0374,
                              1.3,
                              -0.3519,
                              1.7,
                              -0.8754,
                              2.0,
                              -1.3306,
                              2.3,
                              -1.8192,
                              2.4,
                              -1.9867,
                              2.7,
                              -2.4973,
                              3.0,
                              -3.0151,
                              3.3,
                              -3.5362,
                              3.7,
                              -4.2332,
                              4.0,
                              -4.7566,
                              4.2,
                              -5.1057,
                              6.0,
                              -8.2487
                        ]
                  },
                  {
                        "Thickness": 40,
                        "CNRatioSOMI": 12.465753424657533,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.021112,
                        "RHOD": 1.44,
                        "Soil_pH": 7.6,
                        "SMfromPF": [
                              -1.0,
                              0.4248,
                              1.0,
                              0.4106,
                              1.3,
                              0.3972,
                              1.7,
                              0.3678,
                              2.0,
                              0.3389,
                              2.3,
                              0.3079,
                              2.4,
                              0.2977,
                              2.7,
                              0.2679,
                              3.0,
                              0.2404,
                              3.3,
                              0.2156,
                              3.7,
                              0.1864,
                              4.0,
                              0.1672,
                              4.2,
                              0.1555,
                              6.0,
                              0.0828
                        ],
                        "CONDfromPF": [
                              -1.0,
                              0.9594,
                              1.0,
                              0.0224,
                              1.3,
                              -0.2954,
                              1.7,
                              -0.8248,
                              2.0,
                              -1.2846,
                              2.3,
                              -1.7771,
                              2.4,
                              -1.9457,
                              2.7,
                              -2.4596,
                              3.0,
                              -2.9803,
                              3.3,
                              -3.5041,
                              3.7,
                              -4.2045,
                              4.0,
                              -4.7305,
                              4.2,
                              -5.0813,
                              6.0,
                              -8.2394
                        ]
                  },
                  {
                        "Thickness": 100,
                        "CNRatioSOMI": 12.73049645390071,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.020822,
                        "RHOD": 1.45,
                        "Soil_pH": 7.6,
                        "SMfromPF": [
                              -1.0,
                              0.4288,
                              1.0,
                              0.4162,
                              1.3,
                              0.4046,
                              1.7,
                              0.3793,
                              2.0,
                              0.3543,
                              2.3,
                              0.3271,
                              2.4,
                              0.318,
                              2.7,
                              0.2911,
                              3.0,
                              0.2659,
                              3.3,
                              0.2426,
                              3.7,
                              0.2146,
                              4.0,
                              0.1958,
                              4.2,
                              0.1842,
                              6.0,
                              0.1075
                        ],
                        "CONDfromPF": [
                              -1.0,
                              0.7326,
                              1.0,
                              -0.2477,
                              1.3,
                              -0.572,
                              1.7,
                              -1.1101,
                              2.0,
                              -1.5773,
                              2.3,
                              -2.0787,
                              2.4,
                              -2.2506,
                              2.7,
                              -2.7747,
                              3.0,
                              -3.3062,
                              3.3,
                              -3.8413,
                              3.7,
                              -4.5571,
                              4.0,
                              -5.0947,
                              4.2,
                              -5.4533,
                              6.0,
                              -8.6815
                        ]
                  }
            ],
            "SubSoilType": {
                  "CNRatioSOMI": 12.73049645390071,
                  "CRAIRC": 0.03,
                  "FSOMI": 0.020822,
                  "RHOD": 1.45,
                  "Soil_pH": 7.6,
                  "Thickness": 100,
                  "SMfromPF": [
                        -1.0,
                        0.4288,
                        1.0,
                        0.4162,
                        1.3,
                        0.4046,
                        1.7,
                        0.3793,
                        2.0,
                        0.3543,
                        2.3,
                        0.3271,
                        2.4,
                        0.318,
                        2.7,
                        0.2911,
                        3.0,
                        0.2659,
                        3.3,
                        0.2426,
                        3.7,
                        0.2146,
                        4.0,
                        0.1958,
                        4.2,
                        0.1842,
                        6.0,
                        0.1075
                  ],
                  "CONDfromPF": [
                        -1.0,
                        0.7326,
                        1.0,
                        -0.2477,
                        1.3,
                        -0.572,
                        1.7,
                        -1.1101,
                        2.0,
                        -1.5773,
                        2.3,
                        -2.0787,
                        2.4,
                        -2.2506,
                        2.7,
                        -2.7747,
                        3.0,
                        -3.3062,
                        3.3,
                        -3.8413,
                        3.7,
                        -4.5571,
                        4.0,
                        -5.0947,
                        4.2,
                        -5.4533,
                        6.0,
                        -8.6815
                  ]
            }
      }
}