{
      "RDMSOL": 100,
      "SoilProfileDescription": {
            "PFWiltingPoint": 4.2,
            "PFFieldCapacity": 2.0,
            "SurfaceConductivity": 70,
            "GroundWater": false,
            "SoilLayers": [
                  {
                        "Thickness": 5,
                        "CNRatioSOMI": 12.333333333333334,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.053649999999999996,
                        "RHOD": 0.93,
                        "Soil_pH": 6.8,
                        "SMfromPF": [
                              -1.0,
                              0.5718,
                              1.0,
                              0.5523,
                              1.3,
                              0.5327,
                              1.7,
                              0.4879,
                              2.0,
                              0.4431,
                              2.3,
                              0.395,
                              2.4,
                              0.3792,
                              2.7,
                              0.3339,
                              3.0,
                              0.2929,
                              3.3,
                              0.2566,
                              3.7,
                              0.2151,
                              4.0,
                              0.1886,
                              4.2,
                              0.1728,
                              6.0,
                              0.0808
                        ],
                        "CONDfromPF": [
                              -1.0,
                              1.5304,
                              1.0,
                              0.6542,
                              1.3,
                              0.3319,
                              1.7,
                              -0.2286,
                              2.0,
                              -0.7321,
                              2.3,
                              -1.2807,
                              2.4,
                              -1.4699,
                              2.7,
                              -2.0483,
                              3.0,
                              -2.636,
                              3.3,
                              -3.228,
                              3.7,
                              -4.02,
                              4.0,
                              -4.6148,
                              4.2,
                              -5.0115,
                              6.0,
                              -8.583
                        ]
                  },
                  {
                        "Thickness": 10,
                        "CNRatioSOMI": 8.162544169611309,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.013397999999999998,
                        "RHOD": 1.25,
                        "Soil_pH": 6.8,
                        "SMfromPF": [
                              -1.0,
                              0.4802,
                              1.0,
                              0.4609,
                              1.3,
                              0.4405,
                              1.7,
                              0.3937,
                              2.0,
                              0.3481,
                              2.3,
                              0.3009,
                              2.4,
                              0.2858,
                              2.7,
                              0.2436,
                              3.0,
                              0.207,
                              3.3,
                              0.1758,
                              3.7,
                              0.1415,
                              4.0,
                              0.1205,
                              4.2,
                              0.1084,
                              6.0,
                              0.0446
                        ],
                        "CONDfromPF": [
                              -1.0,
                              1.5235,
                              1.0,
                              0.6993,
                              1.3,
                              0.3742,
                              1.7,
                              -0.2015,
                              2.0,
                              -0.722,
                              2.3,
                              -1.2888,
                              2.4,
                              -1.484,
                              2.7,
                              -2.0798,
                              3.0,
                              -2.6843,
                              3.3,
                              -3.2926,
                              3.7,
                              -4.106,
                              4.0,
                              -4.7166,
                              4.2,
                              -5.1239,
                              6.0,
                              -8.7901
                        ]
                  },
                  {
                        "Thickness": 15,
                        "CNRatioSOMI": 18.986175115207374,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.023895999999999997,
                        "RHOD": 1.43,
                        "Soil_pH": 6.9,
                        "SMfromPF": [
                              -1.0,
                              0.4247,
                              1.0,
                              0.4086,
                              1.3,
                              0.3934,
                              1.7,
                              0.3603,
                              2.0,
                              0.3286,
                              2.3,
                              0.2952,
                              2.4,
                              0.2843,
                              2.7,
                              0.2529,
                              3.0,
                              0.2244,
                              3.3,
                              0.199,
                              3.7,
                              0.1695,
                              4.0,
                              0.1504,
                              4.2,
                              0.139,
                              6.0,
                              0.07
                        ],
                        "CONDfromPF": [
                              -1.0,
                              1.0504,
                              1.0,
                              0.1165,
                              1.3,
                              -0.2085,
                              1.7,
                              -0.752,
                              2.0,
                              -1.2236,
                              2.3,
                              -1.728,
                              2.4,
                              -1.9005,
                              2.7,
                              -2.4257,
                              3.0,
                              -2.9573,
                              3.3,
                              -3.4919,
                              3.7,
                              -4.2066,
                              4.0,
                              -4.7432,
                              4.2,
                              -5.101,
                              6.0,
                              -8.3227
                        ]
                  },
                  {
                        "Thickness": 30,
                        "CNRatioSOMI": 13.313253012048195,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.012818000000000001,
                        "RHOD": 1.59,
                        "Soil_pH": 7.1,
                        "SMfromPF": [
                              -1.0,
                              0.3817,
                              1.0,
                              0.3705,
                              1.3,
                              0.36,
                              1.7,
                              0.3369,
                              2.0,
                              0.3139,
                              2.3,
                              0.2888,
                              2.4,
                              0.2804,
                              2.7,
                              0.2557,
                              3.0,
                              0.2326,
                              3.3,
                              0.2113,
                              3.7,
                              0.1859,
                              4.0,
                              0.169,
                              4.2,
                              0.1586,
                              6.0,
                              0.0907
                        ],
                        "CONDfromPF": [
                              -1.0,
                              0.8113,
                              1.0,
                              -0.1388,
                              1.3,
                              -0.4505,
                              1.7,
                              -0.965,
                              2.0,
                              -1.41,
                              2.3,
                              -1.8863,
                              2.4,
                              -2.0495,
                              2.7,
                              -2.5466,
                              3.0,
                              -3.0505,
                              3.3,
                              -3.5575,
                              3.7,
                              -4.2357,
                              4.0,
                              -4.745,
                              4.2,
                              -5.0846,
                              6.0,
                              -8.1428
                        ]
                  },
                  {
                        "Thickness": 40,
                        "CNRatioSOMI": 15.906040268456376,
                        "CRAIRC": 0.03,
                        "FSOMI": 0.013746000000000001,
                        "RHOD": 1.64,
                        "Soil_pH": 7.2,
                        "SMfromPF": [
                              -1.0,
                              0.3657,
                              1.0,
                              0.3565,
                              1.3,
                              0.3478,
                              1.7,
                              0.3281,
                              2.0,
                              0.3078,
                              2.3,
                              0.2852,
                              2.4,
                              0.2775,
                              2.7,
                              0.2547,
                              3.0,
                              0.2331,
                              3.3,
                              0.2131,
                              3.7,
                              0.1889,
                              4.0,
                              0.1727,
                              4.2,
                              0.1627,
                              6.0,
                              0.0961
                        ],
                        "CONDfromPF": [
                              -1.0,
                              0.6969,
                              1.0,
                              -0.2312,
                              1.3,
                              -0.5324,
                              1.7,
                              -1.0322,
                              2.0,
                              -1.468,
                              2.3,
                              -1.9374,
                              2.4,
                              -2.0986,
                              2.7,
                              -2.591,
                              3.0,
                              -3.0909,
                              3.3,
                              -3.5945,
                              3.7,
                              -4.2684,
                              4.0,
                              -4.7745,
                              4.2,
                              -5.1122,
                              6.0,
                              -8.152
                        ]
                  }
            ],
            "SubSoilType": {
                  "CNRatioSOMI": 15.906040268456376,
                  "CRAIRC": 0.03,
                  "FSOMI": 0.013746000000000001,
                  "RHOD": 1.64,
                  "Soil_pH": 7.2,
                  "Thickness": 40,
                  "SMfromPF": [
                        -1.0,
                        0.3657,
                        1.0,
                        0.3565,
                        1.3,
                        0.3478,
                        1.7,
                        0.3281,
                        2.0,
                        0.3078,
                        2.3,
                        0.2852,
                        2.4,
                        0.2775,
                        2.7,
                        0.2547,
                        3.0,
                        0.2331,
                        3.3,
                        0.2131,
                        3.7,
                        0.1889,
                        4.0,
                        0.1727,
                        4.2,
                        0.1627,
                        6.0,
                        0.0961
                  ],
                  "CONDfromPF": [
                        -1.0,
                        0.6969,
                        1.0,
                        -0.2312,
                        1.3,
                        -0.5324,
                        1.7,
                        -1.0322,
                        2.0,
                        -1.468,
                        2.3,
                        -1.9374,
                        2.4,
                        -2.0986,
                        2.7,
                        -2.591,
                        3.0,
                        -3.0909,
                        3.3,
                        -3.5945,
                        3.7,
                        -4.2684,
                        4.0,
                        -4.7745,
                        4.2,
                        -5.1122,
                        6.0,
                        -8.152
                  ]
            }
      }
}